### ISSUE TITLE
Does parallel=True work during training?

### ISSUE THREAD

**Issue by ribas591** [perpetual-ml/perpetual#2]
Hello there!

Thank you for an interesting project!

I wanted to try out the project on my own data set.
Unfortunately, the training time is very long. And despite the flag value, it seems that all the training is done in single-threaded mode.
For example, here is the execution time on a tiny fraction of the dataset  with the flag in use (`CPU times: user 15.2 s, sys: 29.5 s, total: 44.6 s`) and the other one without (`CPU times: user 15.8 s, sys: 30.1 s, total: 45.8 s`). They are more or less the same. 
Is that how it should be? Or am I doing things wrong?

**Comment by deadsoul44** [comment]
Hello, parallelism has little effect currently. A new version will be released in a couple of days with improved parallelism.

**Comment by ribas591** [comment]
That's great to hear. I'll be happy to test the new version when it's ready.

**Comment by deadsoul44** [comment]
Version `0.3.8` is released with multi-output support but no parallelism improvement. Parallelism needs more effort than expected due to rayon. See: https://github.com/rayon-rs/rayon/issues/1184

I am trying to find a solution with or without rayon.
