### ISSUE TITLE
Cannot call ".json_dump" before fit because .booster has not been assigned

### ISSUE THREAD

**Issue by muhlbach** [perpetual-ml/perpetual#21]
This
```
from perpetual import PerpetualBooster
model = PerpetualBooster()
model.json_dump()
```
will raise an `AttributeError: 'PerpetualBooster' object has no attribute 'booster'`, because the call is directed to `self.booster`, which is not set before fitting. 
My use case is that before I call .fit(), I check if I have called it before (as it is expensive) by hashing (using pickle/dill) the model instance together with the fit parameters (data). This will fail.

**Comment by deadsoul44** [comment]
`v0.6.1` is released with the fix.
