### ISSUE TITLE
Expose all fit args at init time

### ISSUE THREAD

**Issue by muhlbach** [perpetual-ml/perpetual#24]
Would you be able to optionally expose these fit parameters at init time? Similar to how FLAML does it, one could set these initially and then if they are provided at fit time, they will overwrite the initial ones. The upshot is that many models are being initialized and then passed through a common fit interface (like `fit.(X,y)`, but one might want to have set, e.g., the budget beforehand.

```
budget: float = 1.0,
alpha: Union[float, None] = None,
reset: Union[bool, None] = None,
categorical_features: Union[Iterable[int], Iterable[str], str, None] = "auto",
timeout: Union[float, None] = None,
iteration_limit: Union[int, None] = None,
memory_limit: Union[float, None] = None,
```

**Comment by deadsoul44** [comment]
Available in new release: `v0.7.0`
