### ISSUE TITLE
Can you share how budget works ?

### ISSUE THREAD

**Issue by lcrmorin** [perpetual-ml/perpetual#8]
I am trying to understand this library. Notably how budget scale runtime:

- How does run time (measured in real time) scale with budget ?
- When benchmarking it seems you go from 56x speed up to 41x speed up when you go from budget 1 to budget 2.1. This speed up look insane compared to lgbm that is considered very fast. Can you clarify how is this speed up obtained ? (it seems you compare to 100 lgbm runs)

**Comment by deadsoul44** [comment]
Hello,

- Run time vs. budget depends on the data but here are the rough results for California Housing data:

1. budget=1.0 -> wall time=10 sec
2. budget=1.5 -> wall time=20 sec
3. budget=2.1 -> wall time=80 sec

- Yes, it is compared to 100 hyperparameter optimization iterations. The budget is adjusted to achieve the same test metric.
