### ISSUE TITLE
Sdist availability

### ISSUE THREAD

**Issue by thewchan** [perpetual-ml/perpetual#9]
Hi, I'm interesting in making perpetual on Conda Forge, however to do so we do need the sdist release be made available on PyPI or Github. Would that be possible?

**Comment by deadsoul44** [comment]
We use maturin to build the package. From maturin docs:

https://www.maturin.rs/distribution
"""
If a pyproject.toml with a [build-system] entry is present, maturin can build a source distribution of your package when --sdist is specified. The source distribution will contain the same files as cargo package. To only build a source distribution, use the maturin sdist command.
"""

If this is enough for conda-forge, I can create a new release. Let me know if something more needed.

**Comment by thewchan** [comment]
@deadsoul44 Thanks I think that's enough, we just need a tarball of the source instead of a wheel file

**Comment by deadsoul44** [comment]
Maturin build fails due to a bug when --sdist specified. 

https://github.com/PyO3/maturin/issues/2244

After the new maturin release with a fix, I will re-try to build.

**Comment by deadsoul44** [comment]
`v0.6.2` is released with `--sdist` option. A `.tar.gz` file is available in the files section. 

https://pypi.org/project/perpetual/#files

Could you please try to release the package to conda-forge channel?

**Comment by thewchan** [comment]
I will begin work; @deadsoul44 would you like to be listed as a maintainer? Generally the work involved is quite minimal as the CI infrastructure automatically picks up a new release when it's made on PyPI.

**Comment by deadsoul44** [comment]
Yes, add me as a maintainer. Thanks a lot.

**Comment by thewchan** [comment]
@deadsoul44 working on the recipe here https://github.com/conda-forge/staged-recipes/pull/28082; you can post a comment there to approve being added as a maintainer. Thanks@

**Comment by deadsoul44** [comment]
Commented there to be added as a maintainer.

**Comment by deadsoul44** [comment]
Perpetual is available on conda-forge channel. Thanks for the contribution.

https://anaconda.org/conda-forge/perpetual
